name: local_final
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.5
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  assets:
    - assets/loocal.png
    - assets/home1.jpg
    - assets/home2.jpg
    - assets/home3.jpg
    - assets/home4.jpg
    - assets/home5.jpg # Relative path only!

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/loocal-logo.png"  # path to your icon file
